# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b037eaa0e8a778820728676e2d9baf25910aeac863e233b34557449f5d167b652130e90d47622f27f53693cd1ad9e5e70ef1180bca1896ad87b2929644866273

test:
  secret_key_base: 95e3c9badf043311d512b719324ecb0e79f499a1210b33d48f55683ee794cd1aa9654966a1f26f9fc9c8061c07d1ecb37a23bf82a68c69c67ad00cc220b4f631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
